### ISSUE TITLE
simplify

### ISSUE THREAD

**Issue by ghost** [goetzk/tendenci-community#2]
I would add the following: 

tendenci needs to be simplified. There are at the moment just _too many_ functions. This is an unnecessary burden on everyone and everything. Developers, maintainers, documentation, deployment. 

Some apps should be removed and offered as plugins. A good example: videos. It makes no sense to have an own video app, given youtube, vimeo, etc.

**Comment by goetzk** [comment]
Thanks for the suggestion - you are right that there are many many applications! I get the impression Tendenci is supposed to be "Batteries included" (python style); many of the applications were merged in to core for (IIRC) Tendenci 7.

In your view would it be preferable to have everything in the same application but disabled by default or is it your opinion applications should all be split out?

Karl.

**Comment by ghost** [comment]
cc @jennyq @eschipul 

Core functions that should be available:
- Newsletter
- User management
- Events
- Calendar (improved)
- Forms
- News

To be disabled. But left in the installation for the user to activate.
- Forums, 
- Directories
- Staff
- Jobs
- Resumes
- Industries

Others can be really removed and left as plugins. 
- Videos (this can be really deprecated)
- Redirects
- Careers
- Educations (what is this?)
- Stories Pages and news are already there. No point to have an extra app for stories. There are also articles and cases. Is that all really needed?
- And some more.

**Comment by goetzk** [comment]
Thank you ghost (sorry I didn't reply while you still had an account!); I've updated the document.
